services:
  messageboy-server:
    image: messageboy-server:latest
    container_name: messageboy-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./configs/server.toml:/app/configs/server.toml:ro
