# MessageBoy Client 配置文件

[Client]
ServerURL = "http://localhost:8080"
Token = "7f88389cb1d33dfed05f1a8f193e55f278f2b493a861d07a9bbfd89a80c394b7"

[Connection]
ReconnectInterval = 5
MaxReconnectInterval = 60
HeartbeatInterval = 30

[Logging]
Level = "info"
File = ""

[Forwarder]
BufferSize = 32768
ConnectTimeout = 10
IdleTimeout = 300
