# MessageBoy Client 配置文件

[Client]
ServerURL = "http://localhost:8080"
Token = "f0bbed96501e47cf4b27ee8078031efdf3e42b8feab5733abaeae22ea74314e6"

[Connection]
ReconnectInterval = 5
MaxReconnectInterval = 60
HeartbeatInterval = 30

[Logging]
Level = "info"
File = ""

[Forwarder]
BufferSize = 32768
ConnectTimeout = 10
IdleTimeout = 300
